[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true
runOnSave = false
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[runner]
magicEnabled = false
fastReruns = false

[development]
watchWheel = false

[theme]
primaryColor = "#2f81f7"
backgroundColor = "#0d1117"
secondaryBackgroundColor = "#161b22"
textColor = "#c9d1d9"
font = "sans serif"
