[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true
# ESTO MATA EL BUCLE: Desactiva el reinicio automático al detectar cambios
runOnSave = false
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[runner]
magicEnabled = false
fastReruns = false

[development]
watchWheel = false
